services:
  app:
    build: .
    container_name: mongle-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    mem_limit: 4g
    environment:
      - JAVA_OPTS=-Xms1g -Xmx3g
    env_file:
      - .env
    networks:
      - mongle-net
    restart: on-failure
    volumes:
      - ./config/keys/private_key.pem:/app/keys/private_key.pem

  db:
    image: mysql:8.0
    container_name: mongle-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mongle-net
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: mongle-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - mongle-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mongle-net:
    driver: bridge

volumes:
  db-data:
  redis-data: