# ===================================================
# Spring Boot 및 서버 설정
# ===================================================
server:
  forward-headers-strategy: native

spring:
  config:
    import:
      - security-config.yml

  # ===================================================
  # 데이터베이스 및 JPA 설정
  # ===================================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/mongle}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
  flyway:
    baseline-on-migrate: true

  # ===================================================
  # Redis 설정
  # ===================================================
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  # ===================================================
  # AWS 서비스 설정
  # ===================================================
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      sqs:
        endpoint: ${SQS_ENDPOINT}

  # ===================================================
  # 이메일 발송(Spring Mail) 설정
  # ===================================================
  mail:
    host: email-smtp.ap-northeast-2.amazonaws.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# ===================================================
# 애플리케이션 커스텀 설정
# ===================================================
app:
  mail:
    from-address: "hello@mongle.site"
  security:
    rate-limit:
      duration-minutes: 5
      max-requests: 10

# ===================================================
# Mongle 서비스 관련 커스텀 설정
# ===================================================
mongle:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
      presigned-url-expiration-minutes: ${PUT_PRESIGNED_URL_EXPIRATION_MIN}
    cloudfront:
      domain: ${CLOUDFRONT_DOMAIN}
      private-key-file-path: ${CLOUDFRONT_PRIVATE_KEY_FILE_PATH}
      key-pair-id: ${CLOUDFRONT_KEY_PAIR_ID}
      presigned-url-expiration-minutes: ${GET_PRESIGNED_URL_EXPIRATION_MIN}
    sqs:
      post-file-update-queue-name: "mongle-post-file-update-queue"
  batch:
    manual-s2seed:
      enabled: true

# ===================================================
# Actuator (헬스 체크 및 메트릭) 설정
# ===================================================
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus
      path-mapping:
        health: health
        prometheus: actuator/prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: mongle-app