ALTER TABLE block
    MODIFY COLUMN created_date TIMESTAMP(6) NOT NULL;

ALTER TABLE comment
    MODIFY COLUMN created_date TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN updated_date TIMESTAMP(6) NOT NULL;

ALTER TABLE dynamic_cloud
    MODIFY COLUMN created_date TIMESTAMP(6) NOT NULL;

ALTER TABLE member
    MODIFY COLUMN created_date TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN updated_date TIMESTAMP(6) NOT NULL;

ALTER TABLE post
    MODIFY COLUMN created_date TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN expired_at TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN updated_date TIMESTAMP(6) NOT NULL;

ALTER TABLE reaction
    MODIFY COLUMN created_date TIMESTAMP(6) NOT NULL;

ALTER TABLE report
    MODIFY COLUMN created_date TIMESTAMP(6) NOT NULL;